### ISSUE TITLE
A few built-in comparators would be useful

### ISSUE THREAD

**Issue by yandongliu** [uber/doubles#100]
e.g. ANY in `mock` that allows us to skip certain argument comparison, or StrContains/ContainsKeyValue as in `mox` that verify part of the input, etc. Should be straightforward to implement.

I was thinking a recording object would be helpful as well. Say instead of passing in a well defined input to `with_args()` we can simply pass in an object that records what occurs to it and it'll be much easier to partially verify the correctness of the arguments. Something like:
```
class Foo(object):
   def bar(name, age)
     ...
foo = Foo()
expect(foo).bar.with_args(recording).once()
foo.bar('anything', 22)
assert recording.age == 22
```

I can have a pull request if you guys don't have the bandwidth.

**Comment by toddsifleet** [comment]
@yandongliu we decided not to include this functionality in doubles for partial matches I built a different library https://github.com/toddsifleet/equals to accomplish this.

The recording strategy breaks the idea that all allowance should be set before the calls are made.  Doing assertions after a call is made can be forgotten which can miss bugs.
