### ISSUE TITLE
False positive MockExpectationError

### ISSUE THREAD

**Issue by denbeigh2000** [uber/doubles#106]
Since upgrading to doubles 1.2.0, our unit tests have started failing with a MockExpectationError, with the following message:
`MockExpectationError: Excepted 'close' to be called 1 time but was called 2 times on [instance] with any args, but was not.`

Pinning doubles to 1.1.3 resolves this issue.
We are testing using pytest 2.9.0 to run our tests.

**Comment by toddsifleet** [comment]
This was an issue with a py.test fixture not with doubles.
