### ISSUE TITLE
Wildcard argument matching support

### ISSUE THREAD

**Issue by clin88** [uber/doubles#108]
This is a feature request for the ability to support extensions to argument matching behavior.

For example, the Java mocking library [mockito](https://mockito.googlecode.com/hg-history/1.6/javadoc/org/mockito/Matchers.html) supports a wide array of argument matchers. This reduces coupling between the test and parameters irrelevant to the test.

Case in point:

```
    allow(tchannel).thrift(
        UserGateway.userstore_client.getUser(userUuid=str(user_uuid)),
        timeout=config.get('populous.timeout')
    ).and_return_future(
        mock.Mock(body=T)
    )
```

In this test, I don't really care what the timeout is. But to mock correctly, I still have to specify it. 

Similarly, mock also has wildcard support in the form of mock.ANY etc.

**Comment by toddsifleet** [comment]
@clin88 I wanted to keep this as a different library, which is why I built [equals](https://github.com/toddsifleet/equals).

For this example you could do `timeout=equals.any_number` or `timeout=equals.any_number.between(1, 10)`
