### ISSUE TITLE
Tag for 1.2.1

### ISSUE THREAD

**Issue by michaeljs1990** [uber/doubles#116]
It seems that the tags in this repository are starting to lag behind the pypi packages. Would you be able to tag out the 1.2.1 version and future updates to make it easier to keep track of what code is in the pypi release.

**Comment by Subzidion** [comment]
It looks like the changelog is up to date and there is a [GitHub tag for 1.2.1](https://github.com/uber/doubles/releases/tag/1.2.1). Unless I'm misunderstanding something, I believe this issue can be closed.
