### ISSUE TITLE
unexpected behaviour on TestCase.setUp() method 

### ISSUE THREAD

**Issue by steeeveb** [uber/doubles#119]
Hello,
when I moved the construction of my objects under test to the setUp method my tests stopped to work because no one calls the teardown function anymore. After taking a look inside of the doubles.unittest.TestCase class I understood that I have to call the super().setUp() method.
SetUp method should be only a hook and this is not what you'd expect from a replacement of the unittest original TestCase. 
I'm wondering if it would be feasible to move the teardown registration to the __init__ of TestCase.

thank you

**Comment by skudriashev** [comment]
@steeeveb do you have an example?

**Comment by steeeveb** [comment]
yes, of course, I'll try to reproduce the thing(after 2 years :D). From what I see now the implementation hasn't changed so I bet the problem is still there

**Comment by steeeveb** [comment]
here you have the test already present in the test suit modified for showing the unexpected behaviour 
https://gist.github.com/steeeveb/7ecec116fc08d87c3c3c8835d725511f

**Comment by skudriashev** [comment]
@steeeveb why don't you want to call `super.setUp` if when you inherit you suppose to do that? :) Anyway please consider the following code:

```python
import unittest

from doubles.instance_double import InstanceDouble
from doubles.targets.expectation_target import expect


class UnittestIntegration(unittest.TestCase):

    def setUp(self):
        self.state = {}

    def runTest(self):
        subject = InstanceDouble('doubles.testing.User')

        expect(subject).instance_method.never()
```

This is how it is expected to work (I would still use `super.setUp` in any case).

**Comment by skudriashev** [comment]
I don't consider this to be an issue, so closing this one. Please feel free to reopen if you have other questions. Thanks.

**Comment by steeeveb** [comment]
The point is, in my opinion, that doubles.TestCase is sold as a replacement of unittest.TestCase where setUp() is a hook and never need the super call. In this way you have to know the implementation to use it, because is different from the original.

**Comment by skudriashev** [comment]
> In this way you have to know the implementation to use it, because is different from the original.

Exactly :)
