### ISSUE TITLE
DeprecationWarning from inspect

### ISSUE THREAD

**Issue by tmartyny** [uber/doubles#136]
File raising the warning: doubles/doubles/allowance.py

Warning raised: 
```
doubles/allowance.py:35: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```

**Comment by skudriashev** [comment]
@tmartyny I've just pushed fix https://github.com/uber/doubles/commit/ab5de75df0470ab7300401a8c5f905d000a618e0. Can you please install master and confirm it works?

**Comment by tmartyny** [comment]
👍 Thanks Stanislav for the rapid response on that! Cleared it right up.

**Comment by skudriashev** [comment]
@tmartyny thanks for raising this ;)
