### ISSUE TITLE
Confusing behavior when overwriting previous mocks/stubs

### ISSUE THREAD

**Issue by UberFarmer** [uber/doubles#61]
It seems that more specific stubs/mocks always have precedence over more generic ones, which has caused me some amount of pain and confusion. 

In my test suites, I use the following pattern a lot, where I set up default behavior for the entire function-in-test during setup, and then only vary portions of the function-in-test during each individual test method. However, there are multiple times where I have encountered the following situation:

```python
class TestStuff(object):
    def setup(self):
        allow(Module).foo.with_args('baz').and_return('giraffe')

    def test_something(self):
        allow(Module).foo.and_return('hippo')
        Module.foo('baz')  # Looks like it should return 'hippo', but will return 'giraffe'
```

Is this expected behavior? (It seems to me like a behavior that would make more sense is that mocks/stubs should be tried in order from most recent until earliest, until one works.) If this is the intended behavior, can it be documented? Either way, can we add a function that will let me clear all mocks/stubs from a method and return it to normal, so I can be sure that only the mocks/stubs specified after the 'clear' will be in effect?

**Comment by toddsifleet** [comment]
@UberFarmer this is the intended behavior, see the code from method_double.py:

    for allowance in self._allowances:
        if allowance.satisfy_exact_match(args, kwargs):
            return allowance

    for allowance in self._allowances:
        if allowance.satisfy_any_args_match():
            return allowance

I'm not sure we want to change that, it could break existing tests.  I like the idea of adding some sort of doubles.clear() method though.  It could be general and clear all mocks/expectations, or it could take arguments and only clear the allowances on the supplied objects.  e.g.

    doubles.clear(Module)

would clear all allowances on `Module` but leave everything else intact.   Any thoughts?

**Comment by UberFarmer** [comment]
Okay, this sounds good.

Why not both?
```
doubles.clear(Module)
```
for clearing a specific module, and
```
doubles.clear_all()
```
for clearing all mocks/expectations?

**Comment by toddsifleet** [comment]
@UberFarmer teardown() does `clear` does.  It removes expectations/allowances (without verifying them). I'm not sure it is the best name but you can use it.
